set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+=n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

set belloff=all
set novisualbell

" Enable syntax highlighting
syntax enable

" Use UTF-8 as standard encoding
set encoding=utf-8

" Display line numbers in left margin
set number
highlight LineNr ctermfg=darkgray

" Expand tabs and indents to four spaces
set expandtab
set shiftwidth=4
set softtabstop=4

" Enable completion menu in command mode
set wildmenu
set wildmode=longest:full,full

" Highlight all matches for current search pattern
set hlsearch
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>

" Show current command in status line while it is typed
set showcmd

" Keep indent from current line when starting a new one
set autoindent

" Enable file type detection and automatic indentation
filetype plugin indent on

" Use X clipboard
set clipboard=unnamedplus

